### ISSUE TITLE
Version in Package Control is outdated and breaks on 3143

### ISSUE THREAD

**Issue by mcclure** [braver/SublimeRetina#5]
Sublime Text 3143 overhauls the UI majorly. This means new people are being driven to the Retina theme because this is the theme recommended in the forums for people who don't like the new UI. Unfortunately there is a bug in the theme under 3143, as described here

https://forum.sublimetext.com/t/how-can-i-revert-to-the-old-default-ui-theme/31378/3

It results in this ugly thing

![Problem](https://pbs.twimg.com/media/DJt4CtUXcAMbZUP.jpg)

I was going to try to put in a pull request with the fix from the sublime text forum, however it looks like the version here in git actually already contains the fix. It's just the version in Package Control which is outdated. The version Package Control downloads for me has a different panel_button_control from the git version

```
    {
        "class": "panel_button_control",
        "layer0.texture": "Theme - Default/panels.png",
        "layer0.opacity": 0.7,
        "content_margin": [12, 8]
    },
```

So it looks like package control just needs a new build pushed? I'm not sure how to install a theme from git O_o

Thanks!

**Comment by braver** [comment]
> So it looks like package control just needs a new build pushed? I'm not sure how to install a theme from git 

Yeah, I actually requested to remove this from package control a while ago, since the new themes are high dpi I thought it wouldn't be needed anymore. Guess I was wrong 😉Although the removal wasn't complete (you can still download it), it is stopping the new release from propagating properly.

You can clone this repo, or download a zip. Just put it in your Packages dir and make sure to rename it to "Theme - Retina". I guess I should put that in the readme...

**Comment by mcclure** [comment]
Fixed!
